server:
  port: 8123
  servlet:
    context-path: /api
spring:
  application:
    name: nick-picture-backend
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/nick_picture
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: nick
    password: admin
mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: false
    # 仅在开发环境打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDeleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: v1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.nick.nickpicturebackend.controller